// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dispatch-variants/Glassmorphic.tsx": () => import("../components/mockups/dispatch-variants/Glassmorphic.tsx"),
  "./components/mockups/dispatch-variants/MissionControl.tsx": () => import("../components/mockups/dispatch-variants/MissionControl.tsx"),
  "./components/mockups/dispatch-variants/SleekPro.tsx": () => import("../components/mockups/dispatch-variants/SleekPro.tsx")
};
